### PR TITLE
Fix: don't cancel current upload on generic file error. Address #1093, #1216.

### PR DESCRIPTION
**Pull request by jayarjo**

### CODE REVIEW

**Comment by najamelan** [comment]
I'm still seeing a bit strange behavior when it comes down to the http error and the trigger "CancelUpload". onError calls uploadNext.call(up); However, if there is no other files in the queue, the state remains at  plupload.STARTED. Now if you add new files to the queue and call uploader.start() nothing happens, because it's state is already STARTED. Apart from that, I'm calling start() in an event handler on 'filesAdded' because 'autostart' doesn't seem to have any effect for me.

I can file separate issues for these problems if that's deemed useful.

**Comment by najamelan** [comment]
What I'm seeing is that when an http error occurs,  'file.trigger('Error', {' happens, but the function onError is bound to the uploader and not to individual files, so it isn't run. As far as I can tell the code in onError that now depends on 'if( error.code === HTTP_ERROR ) is unreachable, which means that uploadNext never gets called, which would have taken care of putting that state to STOPPED.

**Comment by jayarjo** [comment]
Version of the Plupload that is currently being developed on master branch is quite different from 2.1.x, and - yes, not all event handlers are properly attached at the moment (see https://github.com/moxiecode/plupload/issues/1198).

Btw, autostart is specific to UI Widget and does nothing for pure core implementation.

**Comment by najamelan** [comment]
ok, thanks, that explains what's happening. I'll keep an eye on the evolution of the master branch to see when these issues get resolved.

For now as a workaround I called uploader.stop(); uploader.start() on http errors, and that seems to work.

**Pull request merged**
