### PR TITLE
Drag & Drop support of folders (Chrome >= 21)

### PR DESCRIPTION
**Pull request by tiff**
Chrome 21 implemented the possibility for folder drag & drop.

This patch adds a "relativePath" property to each instance of ``plupload.File``.

Example: http://protonet.github.com/plupload/examples/drag_and_drop.html
More details to the chrome implementation: http://wiki.whatwg.org/wiki/DragAndDropEntries
Chromium issue: http://code.google.com/p/chromium/issues/detail?id=99823

Also this patch makes sure that the default behavior within ``dragover`` is only prevented when the drag contains any files otherwise there will be problems when eg. the ``drop_element`` is a ``<textarea>`` and the user is dragging text around.

### CODE REVIEW

**Comment by tsmgeek** [comment]
I have merged this code into my pluploader.
There is a bug due to the 100 file limit in webkit for readEntries();
You have to iterate over it until entries.length is false then you can process all the found files.
Below is altered code in walkFileSystem() which works.

```
                        function walkFileSystem(directory, callback, error) {
                                if (!callback.pending) {
                                        callback.pending = 0;
                                }
                                if (!callback.files) {
                                        callback.files = [];
                                }

                                callback.pending++;

                                var reader = directory.createReader(),
                                relativePath = directory.fullPath.replace(/^\//, "").replace(/(.+?)\/?$/, "$1/");
                                var allentries = [];

                                function toArray(list) {
                                        return Array.prototype.slice.call(list || [], 0);
                                }
                                var readEntries = function(){
                                reader.readEntries(function(entries) {
                                        if(!entries.length){
                                                callback.pending--;
                                                plupload.each(allentries, function(entry) {
                                                        if (entry.isFile) {
                                                                callback.pending++;
                                                                entry.file(function(File) {
                                                                        File.relativePath = relativePath + File.name;
                                                                        callback.files.push(File);
                                                                        if (--callback.pending === 0) {
                                                                                callback(callback.files);
                                                                        }
                                                                }, error);
                                                        } else {
                                                                walkFileSystem(entry, callback, error);
                                                        }
                                                });
                                                if (callback.pending === 0) {
                                                        callback(callback.files);
                                                }
                                        }else{
                                                allentries = allentries.concat(toArray(entries));
                                                readEntries();
                                        }
                                }, error);
                                };

                                readEntries();
                        }
```

**Comment by mscheper** [comment]
More information about @tsmgeek's fix (since I was just about to submit essentially the same fix): The root cause of the issue is that the code isn't following the [Basic Concepts](https://developer.mozilla.org/en/docs/Web/API/DirectoryReader#basic_concepts) of the DirectoryReader class. See [this StackOverflow post](http://stackoverflow.com/questions/23823548/maximum-files-of-a-directory-that-can-be-read-by-filereaderreadentries-in-javas) for details.

**Comment by jayarjo** [comment]
`relativePath` is now being retrieved where supported and can be accessed on the File object.

@tsmgeek , @mscheper we do not rely on `length` property and check the folders recursively. Can you check the code here: [FileDrop](https://github.com/moxiecode/moxie/blob/master/src/javascript/runtime/html5/file/FileDrop.js).

Since this has been implemented. I'll close this one.

**Comment by foaly-nr1** [comment]
Great news, thanks @jayarjo!

**Comment by pafgoncalves** [comment]
How to make that property be posted?

**Pull request closed without merging**
