### PR TITLE
fix bug

### PR DESCRIPTION
**Pull request by DavidSuns**
To fix issue:
https://github.com/moxiecode/plupload/issues/1374
https://github.com/moxiecode/plupload/issues/1332

### CODE REVIEW

**Comment by jayarjo** [comment]
The point of passing `this` was that it adapted to whatever was the environment. In browser it was becoming `window` automatically. What exactly has changed could you please help to explain?

**Comment by DavidSuns** [comment]
Hi


When i use it by es6 'import', and bundle it into a js file, it can't work in browser,so i add that code.


________________________________
发件人: Davit Barbakadze <notifications@github.com>
发送时间: 2016年11月12日 10:29
收件人: moxiecode/plupload
抄送: David Sun; Author
主题: Re: [moxiecode/plupload] fix bug (#1390)


The point of passing this was that it adapted to whatever was the environment. In browser it was becoming window automatically. What exactly has changed could you please help to explain?

―

**Comment by jayarjo** [comment]
I can't merge your pull request, since it fails in some other scenarios. But thank you for suggestion. I've implemented the fix in [v2.2.0](https://github.com/moxiecode/plupload/releases/tag/v2.2.0).

Would you be so kind and test if it works?

**Comment by DavidSuns** [comment]
yes, of course, thank you for your reply.


________________________________
发件人: Davit Barbakadze <notifications@github.com>
发送时间: 2016年11月14日 19:01
收件人: moxiecode/plupload
抄送: David Sun; Author
主题: Re: [moxiecode/plupload] fix bug (#1390)


I can't merge your pull request, since it fails in some other scenarios. But thank you for suggestion. I've implemented the fix in v2.2.0<https://github.com/moxiecode/plupload/releases/tag/v2.2.0>.

Would you be so kind and test if it works?

―

**Pull request closed without merging**
