### PR TITLE
Add bower.json

### PR DESCRIPTION
**Pull request by dansullivan86**
Adds ability for Plupload to be used with Bower

Also Fixes:
https://github.com/moxiecode/plupload/issues/1111

Also if this gets accepted could you consider registering with Bower?
http://bower.io/docs/creating-packages/#register

### CODE REVIEW

**Comment by Boboss74** [comment]
Version field is now deprecated

https://github.com/bower/spec/blob/master/json.md#version

**Comment by codewizz** [comment]
+1 for bower support!

**Comment by warrendodsworth** [comment]
Defo +1 for bower support!

**Comment by jayarjo** [comment]
We got bower support. Better late than never. Thanks for upvotes.

**Pull request closed without merging**
