### PR TITLE
Update lv.js

### PR DESCRIPTION
**Pull request by kaalis**
2 spelling mistakes in "terrabaiti" and "Pieveinojiet"

### CODE REVIEW

**Comment by jayarjo** [comment]
Sorry, I can't merge this from here. If you want to contribute to the language pack, you should do it from its [Transifex page](https://www.transifex.com/projects/p/plupload/language/lv/).

**Comment by kaalis** [comment]
Thanks.

**Comment by kaalis** [comment]
Transifex looks dead as there is no reply from the team.

**Comment by jayarjo** [comment]
I've added you myself now.

**Comment by kaalis** [comment]
Thanks. Updated 2 strings, at least they are visible to others also.

**Pull request closed without merging**
